import { animationGuide } from '../../data/animationGuide'
import { presetCategories } from '../../utils/searchPresets'
import styles from './DocumentationPage.module.scss'
const sections = [
  ['Introduction', 'Animation Builder lets you configure CSS animations, preview a scene and copy CSS for AEM. The builder uses JavaScript; exported animations use CSS and, for special elements, HTML.'],
  ['Creating elements', 'Use Add element in Elements. Select an element to edit its label, type and content. Its actions menu offers duplication, ordering and deletion. Specialized presets lock the content type they require.'],
  ['Selecting presets', 'Search by name or effect. Quick filters and More filters narrow the catalog. Select a card to apply it; editing its settings keeps the preset name marked as modified.'],
  ['Custom animations', 'Choose Custom animation in Animation. Existing defaults start with zero numeric motion values and an empty animation name. Set a duration above zero in Timing, then adjust the starting transform, opacity and rebound in Advanced.'],
  ['Live Preview', 'Configuration changes replay the scene. On scroll waits for the block to enter the preview viewport; scroll inside the canvas and use Replay to test again. Canvas width and expansion affect only the preview layout.'],
  ['Exporting for AEM', 'Open Generated CSS or use Export CSS in the header. Copy the classes, CSS and required HTML, when shown. Scroll exports rely on the client’s existing abbv-animation / inView behavior. Confirm markup support and final appearance in the actual AEM component.'],
  ['Importing and exporting projects', 'Project contains Import JSON, Export JSON and Restore backup. Projects save locally in this browser and origin. Export JSON for a portable backup. Import replaces the scene and keeps a previous-import backup. New project asks for confirmation and uses that same backup mechanism.'],
]
export default function DocumentationPage() {
  return <article className={styles.page}><header><p>ANIMATION BUILDER</p><h1>Documentation</h1><p>A practical starting point for creating and exporting animations.</p></header><nav aria-label="Documentation sections">{sections.map(([title],index)=><a key={title} href={`#documentation-${index}`}>{title}</a>)}<a href="#documentation-animations">Animation guide</a></nav>{sections.map(([title,body],index)=><section id={`documentation-${index}`} key={title}><h2>{title}</h2><p>{body}</p></section>)}
    <section id="documentation-animations"><h2>Animation guide</h2><p>Explore all {animationGuide.length} presets. These descriptions explain their default settings; changing controls or playback direction changes the result. Duration controls speed, Delay controls the wait before starting, and Easing changes how the movement accelerates and slows down.</p><p>The ◇ beside a control means it has no visual effect with the current settings. Hover over it or focus it with the keyboard for an explanation. The control stays available for experimentation.</p><nav aria-label="Animation families">{presetCategories.map((category, index) => <a key={category} href={`#documentation-family-${index}`}>{category}</a>)}</nav>
      {presetCategories.map((category, index) => <section id={`documentation-family-${index}`} key={category}><h3>{category}</h3><div className={styles.catalog}>{animationGuide.filter(entry => entry.category === category).map(entry => <article className={styles.animation} key={entry.name}><h4>{entry.name}</h4><dl><dt>What it does</dt><dd>{entry.description}</dd><dt>Good for</dt><dd>{entry.goodFor}</dd><dt>Main controls</dt><dd>{entry.controls.join(', ')}.</dd></dl>{entry.note && <p>{entry.note}</p>}</article>)}</div></section>)}
    </section></article>
}
